name: cdiff-biolog-amiga
channels:
- conda-forge
dependencies:
- cycler=0.10.0=py_2
- decorator=4.4.2=py_0
- gpy=1.9.9=py38ha1b04c9_7
- kiwisolver=1.1.0=py38ha0d09dd_1
- matplotlib=3.1.3=py38_0
- numpy=1.18.1=py38h1f821a2_1
- pandas=0.25.3=py38h4f17bb1_0
- paramz=0.9.5=py_0
- pyparsing=2.4.6=py_0
- python-dateutil=2.8.1=py_0
- pytz=2019.3=py_0
- scipy=1.4.1=py38h38b60c6_3
- seaborn=0.10.0=py_1
- six=1.14.0=py_1
- tabulate=0.8.6=py_0